Community Branding Implementation
NateshR/LikeMinds-Flutter-Feed-SX pull request #2
Opened 2022-12-19 22:01 UTC by PaRaDoX50

Implemented Basic and Advanced branding using Local DB (Hive), Models, and Entities.
Used a mock repository for branding data because it is a part of the data SDK.

2022-12-20 06:34 UTC, divyanshgandhilm requested changes
A few changes, and comments

2022-12-20 06:34 UTC, divyanshgandhilm commented on lib/src/data/local_db_service.dart
> +import 'package:feed_sx/src/models/advanced_branding.dart';
If this is a service, it should be in the services folder. The repository can be here.

2022-12-20 06:34 UTC, divyanshgandhilm commented on lib/src/sdk/sdk_service.dart
> +// ignore_for_file: public_member_api_docs, sort_constructors_first
Why is this file called SDK service? Also let's format the files properly with proper return statements and spacing.

2022-12-20 06:34 UTC, divyanshgandhilm commented on lib/src/theme.dart
> +const SizedBox kHorizontalXLargeP = SizedBox(width: kPaddingXLarge);
Really nice addition, this will make it easier!

2022-12-20 11:56 UTC, divyanshgandhilm approved these changes

2022-12-20 11:56 UTC, divyanshgandhilm commented
Let's let @NateshR take a final look as well before merging

2022-12-21 06:28 UTC, NateshR commented on lib/src/data/local/local_db_impl.dart
> +      await brandingBox.delete(brandingKey);
don't we have an update method?

2022-12-21 06:28 UTC, NateshR commented on lib/src/data/local/local_db_impl.dart
> +  final String brandingBoxKey = 'branding_box';
two keys have same value?

2022-12-21 06:28 UTC, NateshR commented on lib/src/data/models/advanced_branding.dart
> +  String toString() =>
what's the use of this

2022-12-21 07:03 UTC, NateshR requested changes

2022-12-21 07:03 UTC, NateshR commented on lib/src/theme.dart
> +const SizedBox kHorizontalXLargeP = SizedBox(width: kPaddingXLarge);
sync name

2022-12-21 08:00 UTC, PaRaDoX50 commented
@NateshR Made the desired changes. PTAL.

2022-12-21 12:25 UTC, NateshR approved these changes

2022-12-21 12:27 UTC, divyanshgandhilm commented
Everything looks good. One thing, why did we create a src folder inside the lib folder? The lib folder does the same job as you are doing right now with src right?

2022-12-21 12:29 UTC, divyanshgandhilm approved these changes

2022-12-21 12:31 UTC, merged